### ISSUE TITLE
If the XML says it is UTF-16, Crack parses it into an empty hash.

### ISSUE THREAD

**Issue by ianterrell** [jnunemaker/crack#2]
Is this desired behavior?

<pre>
>> Crack::XML.parse("&lt;hi>&lt;/hi>")
=> {"hi"=>nil}
>> Crack::XML.parse("<?xml version='1.0' encoding='utf-16'?>&lt;hi>&lt;/hi>")
=> {}
>> Crack::XML.parse("<?xml version='1.0' encoding='utf-8'?>&lt;hi>&lt;/hi>")
=> {"hi"=>nil}
</pre>

**Comment by kiskoza** [comment]
I wasn't able to reproduce this issue on current master. Feel free to reopen the issue if it still occurs for you
