### ISSUE TITLE
Crack breaks Mongoid by adding #attributes method to the String class

### ISSUE THREAD

**Issue by zdennis** [jnunemaker/crack#20]
Crack adds the #attributes method to the String class when parsing xml which conflicts with Mongoid as Mongoid uses respond_to?(:attributes) when determining whether to load associations. 

Crack should likely not be adding #attributes to String. It should use a wrapper class or a subclass if it needs to modify core classes with something library specific.

**Comment by kiskoza** [comment]
It seems to be fixed already. Feel free to reopen the issue if you think otherwise
