### ISSUE TITLE
parsing of XML return a singleton Hash that is not dumpable

### ISSUE THREAD

**Issue by HoneyryderChuck** [jnunemaker/crack#35]
I'm using the parsing engine in order to get hash representation that will be serialized somewhere. In order for it to be serialized, the object cannot be singleton. Turns out, what the parsing function returns is indeed singleton, therefore, not dumpable.

quick example:

<pre>
<code>

xml = '<fx dong="Bing">
<cond>This</cond>
<rank>is</rank>
<freak>freaky</freak>
</fx>'

Marshal.dump Crack::XML.parse(xml)

</code>
</pre>

this returns:  TypeError: singleton can't be dumped

Is it short-term-fixable?

Regards
Tiago

**Comment by kiskoza** [comment]
Seems to be fixed already
