### ISSUE TITLE
Remove `test/` from bundled gem

### ISSUE THREAD

**Issue by parkr** [jnunemaker/crack#65]
Hey folks,

I noticed that this gem is 2.6 MB, 2.5 of which comes from `test/data/large_dataset.json`. Is it necessary to ship the test data with this gem? Perhaps we could get away with just:

- `lib/`
- `crack.gemspec`
- `History`
- `LICENSE`
- `README.md`

What do you think? /cc @bf4

**Comment by parkr** [comment]
<img width="1183" alt="Screen Shot 2020-10-29 at 3 52 05 PM" src="https://user-images.githubusercontent.com/237985/97625475-edfb7780-19fe-11eb-9d20-8d61db051e20.png">

**Comment by bf4** [comment]
Nope, no need to ship tests. Rubygems hasn't supported executing them for ages and I think there's a general pattern of removing them from built gems. You up for a PR?

**Comment by parkr** [comment]
Well, [it looks like I was beaten to it – in 2018!](https://github.com/jnunemaker/crack/pull/61) Crack v0.4.3 (pictured above) included the test data, but v0.4.4 (which I just upgraded to), does not.

Thank you for the quick reply, @bf4, and for being cool with the proposal. Sorry for not checking on the latest version! 🤦

**Comment by bf4** [comment]
Lol
