### ISSUE TITLE
Can't parse the following json

### ISSUE THREAD

**Issue by ricn** [jnunemaker/crack#9]
{
       "name" : "cm:content",
       "isAspect" : false,
       "title" : "Content",
       "description" : "Base Content Object",
      "parent" : {
          "name" : "cm:cmobject",
          "title" : "cmobject",
          "url" : "\/api\/classes\/cm_cmobject"
      },
     "defaultValues" : {
     }, 
     "defaultAspects" : {
          "sys:referenceable" : {
            "name" : "sys:referenceable",
            "title" : "Referenceable",
            "url" : "\/api\/classes\/cm_content\/property\/sys_referenceable"
           },
          "cm:auditable" : {
            "name" : "cm:auditable",
            "title" : "Auditable",
            "url" : "\/api\/classes\/cm_content\/property\/cm_auditable"
           }
      },
      "properties" : {
      "cm:name": {
          "name" : "cm:name",
          "title" : "Name",
          "url" : "\/api\/classes\/cm_content\/property\/cm_name"
        },
      "cm:content": {
          "name" : "cm:content",
          "title" : "Content",
          "url" : "\/api\/classes\/cm_content\/property\/cm_content"
        }
       },  
      "associations" : {
       },  
       "childassociations" : {
    },  
      "url" : "\/api\/classes\/cm_content"  
  }

Only gets a Invalid JSON string (Crack::ParseError). The json should be valid: http://www.jsonlint.com/

Any ideas?

**Comment by kiskoza** [comment]
This seems to be working on current master. Feel free to reopen the issue, if you run into a problem again
